name: Create Temporary GitHub Repository for Client

on:
  workflow_dispatch:
    inputs:
      versioningTool:
        description: "Versioning tool"
        required: true
      hostingType:
        description: "Hosting type"
        required: true
      monitoringTool:
        description: "Monitoring tool"
        required: true
      hostingJarTool:
        description: "Hosting Jar Tool"
        required: true

jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "Ferielkraiem2000"
          git config --global user.email "feriel.benkraiem@ensi-uma.tn"

      - name: Create temporary repository
        id: create_repo
        run: |
          REPO_NAME="temp-repo-${{ github.sha }}"
          curl -H "Authorization: token ${{secrets.GITHUBTOKEN}}" \
               -d '{"name": "'${REPO_NAME}'", "private": false}' \
               https://api.github.com/user/repos
          echo "Repo URL: https://github.com/Ferielkraiem2000/${REPO_NAME}"
          echo "REPO_URL=https://github.com/Ferielkraiem2000/${REPO_NAME}" >> $GITHUB_ENV

      - name: Copy configuration to new repository
        run: |
          FOLDER_PATH="${{ github.event.inputs.versioningTool }}/${{ github.event.inputs.hostingType }}/${{ github.event.inputs.monitoringTool }}/${{ github.event.inputs.hostingJarTool }}"
          REPO_NAME="temp-repo-${{ github.sha }}"
          
          mkdir -p temp_repo
          cp -r ${FOLDER_PATH}/* temp_repo/

          cd temp_repo
          git init
          git config --global user.name "Ferielkraiem2000"
          git config --global user.email "feriel.benkraiem@ensi-uma.tn"
          git branch -M main
          git remote add origin https://${{secrets.GITHUBTOKEN}}@github.com/Ferielkraiem2000/${REPO_NAME}.git
          git add .
          git commit -m "Add configuration for ${FOLDER_PATH}"
          git push -u origin main --force
